import { contextBridge, ipcRenderer, webUtils } from 'electron';
import type {
  AgentEvent,
  AttachAgentPromptSessionInputSourcesInput,
  ContinueAgentPromptSessionInput,
  ArticleGenerationRequest,
  CreatePromptDraftFromContentInput,
  CreateContentDraftChangeInput,
  CreateContentKnowledgeReleaseInput,
  CreateContentProductionHandoffInput,
  CreateSceneCardFromContentInput,
  CreateTeamKnowledgePromptDraftInput,
  ExportContentDraftChangeInput,
  OemSiteConfigRequest,
  ReviewAssetInput,
  AssetFileKind,
  AutoUpdateState,
  BuguEmailCodeSendInput,
  BuguEmailCodeVerifyInput,
  BuguPasswordLoginInput,
  AdvanceContentBatchStageInput,
  BuildContentBatchInput,
  ContentStudioApi,
  CreateSkillInput,
  BuildContentKnowledgeMapInput,
  ExportAssetInput,
  ExportContentKnowledgePackInput,
  ExportMixPackageInput,
  ExportMarkdownInput,
  ExportPlatformDraftInput,
  GenerateContentReviewTasksInput,
  GenerateOverlayCardsInput,
  GenerateBrandKnowledgeBaseInput,
  GenerateIpKnowledgeBaseInput,
  GeneratePromptDraftInput,
  GeneratePromptPackInput,
  GenerateImageSkillInput,
  GenerateSceneCardsInput,
  ImageGenerationRequest,
  AppendShotGenerationLogInput,
  CreateImageProductionTaskInput,
  UpdateImageProductionTaskInput,
  UpdateShotPromptInput,
  ImportContentDraftChangeInput,
  ImportInputSourceFromFileOptions,
  InputSourcePurpose,
  InstallSkillPackageInput,
  RenameSkillInput,
  ReplaceSkillPackageInput,
  KnowledgeSearchInput,
  PromptPack,
  ReferenceReverseRequest,
  RespondAgentPromptActionInput,
  ResolveContentSyncConflictInput,
  RecordPromptDraftCopyInput,
  RecordMixPackageImportEvidenceInput,
  ReadContentKnowledgePackFileInput,
  ReadPlatformDraftCopyTextInput,
  RunTaskInput,
  SubmitContentReviewDecisionInput,
  SubmitContentDraftChangeInput,
  WriteBackContentMaterialCoverageInput,
  RegisterInputSourceInput,
  UpdatePromptDraftInput,
  SaveModelConfigInput,
  SaveSettingsInput,
  SceneCard,
  BrandKnowledgeBaseRecord,
  ContentKnowledgeMapRecord,
  IpKnowledgeBaseRecord,
  SkillRef,
  StageSkillPackageInput,
  SkillWorkspaceInput,
  VideoBreakdownRequest,
  VideoGenerationRequest,
  VideoScriptEvaluationRequest,
  VideoScriptGenerationRequest,
  VideoScriptShotRewriteRequest,
  UpdateCheckOptions,
  StartAgentPromptSessionInput,
  GenerationTaskEvent,
  SubmitGenerationTaskInput,
  UpdateGenerationLogReviewInput,
} from '../shared/types';

const api: ContentStudioApi = {
  authGetSession: () => ipcRenderer.invoke('auth:getSession'),
  authLoginByPassword: (input: BuguPasswordLoginInput) => ipcRenderer.invoke('auth:loginByPassword', input),
  authSendEmailCode: (input: BuguEmailCodeSendInput) => ipcRenderer.invoke('auth:sendEmailCode', input),
  authVerifyEmailCode: (input: BuguEmailCodeVerifyInput) => ipcRenderer.invoke('auth:verifyEmailCode', input),
  authLogout: () => ipcRenderer.invoke('auth:logout'),
  getOemSiteConfig: (input?: OemSiteConfigRequest) => ipcRenderer.invoke('oem:getSiteConfig', input),

  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (input: SaveSettingsInput) => ipcRenderer.invoke('settings:save', input),
  selectWorkspace: () => ipcRenderer.invoke('workspace:select'),

  getUpdateState: () => ipcRenderer.invoke('updates:getState'),
  checkForUpdates: (options?: UpdateCheckOptions) => ipcRenderer.invoke('updates:check', options),
  setAutoUpdateEnabled: (enabled: boolean) => ipcRenderer.invoke('updates:setAutoCheck', enabled),
  openUpdateDownload: () => ipcRenderer.invoke('updates:openDownload'),
  openUpdateReleaseNotes: () => ipcRenderer.invoke('updates:openReleaseNotes'),
  openLogsDirectory: () => ipcRenderer.invoke('updates:openLogsDirectory'),
  onUpdateState: (callback: (state: AutoUpdateState) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: AutoUpdateState) => callback(payload);
    ipcRenderer.on('updates:state', listener);
    return () => ipcRenderer.off('updates:state', listener);
  },

  getModelConfig: () => ipcRenderer.invoke('modelConfig:get'),
  saveModelConfig: (input: SaveModelConfigInput) => ipcRenderer.invoke('modelConfig:save', input),
  getModelCatalog: () => ipcRenderer.invoke('modelConfig:catalog'),

  scanSkills: (workspacePath?: string) => ipcRenderer.invoke('skills:scan', workspacePath),
  installBuiltinSkill: (slug: string, workspacePath: string) => ipcRenderer.invoke('skills:installBuiltin', slug, workspacePath),
  createSkill: (input: CreateSkillInput) => ipcRenderer.invoke('skills:create', input),
  uploadSkillPackage: (workspacePath: string) => ipcRenderer.invoke('skills:package:upload', workspacePath),
  openSkillFolder: (workspacePath: string, skill: SkillRef) => ipcRenderer.invoke('skills:folder:open', workspacePath, skill),
  renameSkill: (input: RenameSkillInput) => ipcRenderer.invoke('skills:rename', input),
  replaceSkillPackage: (input: ReplaceSkillPackageInput) => ipcRenderer.invoke('skills:replacePackage', input),
  uninstallSkill: (input: SkillWorkspaceInput) => ipcRenderer.invoke('skills:uninstall', input),
  readSkillFile: (workspacePath: string | undefined, skill: SkillRef, relativePath: string) => ipcRenderer.invoke('skills:file:read', workspacePath, skill, relativePath),
  getPathForFile: (file: File) => webUtils.getPathForFile(file) || null,
  stageSkillPackage: (input: StageSkillPackageInput) => ipcRenderer.invoke('skills:package:stageDropped', input),
  previewSkillPackage: (packagePath: string, workspacePath?: string) => ipcRenderer.invoke('skills:package:preview', packagePath, workspacePath),
  readSkillPackageFile: (packagePath: string, relativePath: string) => ipcRenderer.invoke('skills:package:readFile', packagePath, relativePath),
  installSkillPackage: (input: InstallSkillPackageInput) => ipcRenderer.invoke('skills:package:install', input),
  onSkillPackageOpenRequest: (callback: (packagePath: string) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, packagePath: string) => callback(packagePath);
    ipcRenderer.on('skills:packageOpenRequest', listener);
    return () => ipcRenderer.off('skills:packageOpenRequest', listener);
  },
  notifySkillPackageOpenReady: () => ipcRenderer.send('skills:packageOpenReady'),
  getSkillFileAssociation: () => ipcRenderer.invoke('skills:fileAssociation:get'),
  setSkillFileAssociationDefault: () => ipcRenderer.invoke('skills:fileAssociation:setDefault'),
  getSkillSelection: (workspacePath: string) => ipcRenderer.invoke('skills:selection:get', workspacePath),
  setSkillEnabled: (workspacePath: string, skill: SkillRef, enabled: boolean) => ipcRenderer.invoke('skills:selection:set', workspacePath, skill, enabled),

  listKnowledgeBases: (workspacePath?: string) => ipcRenderer.invoke('knowledge:list', workspacePath),
  importKnowledgeBaseFromFile: (workspacePath: string) => ipcRenderer.invoke('knowledge:importFromFile', workspacePath),
  installBuiltinKnowledgeBase: (id: string, workspacePath: string) => ipcRenderer.invoke('knowledge:installBuiltin', id, workspacePath),
  searchKnowledge: (input: KnowledgeSearchInput) => ipcRenderer.invoke('knowledge:search', input),

  listPromptPacks: (workspacePath: string) => ipcRenderer.invoke('promptPacks:list', workspacePath),
  generatePromptPack: (input: GeneratePromptPackInput) => ipcRenderer.invoke('promptPacks:generate', input),
  updatePromptPack: (input: PromptPack) => ipcRenderer.invoke('promptPacks:update', input),
  listBrandKnowledgeBases: (workspacePath: string) => ipcRenderer.invoke('brandKnowledgeBases:list', workspacePath),
  generateBrandKnowledgeBase: (input: GenerateBrandKnowledgeBaseInput) => ipcRenderer.invoke('brandKnowledgeBases:generate', input),
  updateBrandKnowledgeBase: (input: BrandKnowledgeBaseRecord) => ipcRenderer.invoke('brandKnowledgeBases:update', input),
  listIpKnowledgeBases: (workspacePath: string) => ipcRenderer.invoke('ipKnowledgeBases:list', workspacePath),
  generateIpKnowledgeBase: (input: GenerateIpKnowledgeBaseInput) => ipcRenderer.invoke('ipKnowledgeBases:generate', input),
  updateIpKnowledgeBase: (input: IpKnowledgeBaseRecord) => ipcRenderer.invoke('ipKnowledgeBases:update', input),
  listSceneCards: (workspacePath: string) => ipcRenderer.invoke('sceneCards:list', workspacePath),
  generateSceneCards: (input: GenerateSceneCardsInput) => ipcRenderer.invoke('sceneCards:generate', input),
  createSceneCardFromContent: (input: CreateSceneCardFromContentInput) => ipcRenderer.invoke('sceneCards:createFromContent', input),
  updateSceneCard: (input: SceneCard) => ipcRenderer.invoke('sceneCards:update', input),
  listContentKnowledgeMaps: (workspacePath: string) => ipcRenderer.invoke('contentKnowledgeMaps:list', workspacePath),
  listContentKnowledgeMapBuildRuns: (workspacePath: string) => ipcRenderer.invoke('contentKnowledgeMapBuildRuns:list', workspacePath),
  buildContentKnowledgeMap: (input: BuildContentKnowledgeMapInput) => ipcRenderer.invoke('contentKnowledgeMaps:build', input),
  updateContentKnowledgeMap: (input: ContentKnowledgeMapRecord) => ipcRenderer.invoke('contentKnowledgeMaps:update', input),
  listContentDraftChanges: (workspacePath: string) => ipcRenderer.invoke('contentDraftChanges:list', workspacePath),
  createContentDraftChange: (input: CreateContentDraftChangeInput) => ipcRenderer.invoke('contentDraftChanges:create', input),
  submitContentDraftChange: (input: SubmitContentDraftChangeInput) => ipcRenderer.invoke('contentDraftChanges:submit', input),
  exportContentDraftChange: (input: ExportContentDraftChangeInput) => ipcRenderer.invoke('contentDraftChanges:export', input),
  importContentDraftChange: (input: ImportContentDraftChangeInput) => ipcRenderer.invoke('contentDraftChanges:import', input),
  listContentKnowledgeReleases: (workspacePath: string) => ipcRenderer.invoke('contentKnowledgeReleases:list', workspacePath),
  createContentKnowledgeRelease: (input: CreateContentKnowledgeReleaseInput) => ipcRenderer.invoke('contentKnowledgeReleases:create', input),
  listContentSyncConflicts: (workspacePath: string) => ipcRenderer.invoke('contentSyncConflicts:list', workspacePath),
  resolveContentSyncConflict: (input: ResolveContentSyncConflictInput) => ipcRenderer.invoke('contentSyncConflicts:resolve', input),
  listContentBatches: (workspacePath: string) => ipcRenderer.invoke('contentBatches:list', workspacePath),
  buildContentBatch: (input: BuildContentBatchInput) => ipcRenderer.invoke('contentBatches:build', input),
  advanceContentBatchStage: (input: AdvanceContentBatchStageInput) => ipcRenderer.invoke('contentBatches:advanceStage', input),
  exportContentKnowledgePack: (input: ExportContentKnowledgePackInput) => ipcRenderer.invoke('contentKnowledgePack:export', input),
  readContentKnowledgePackFile: (input: ReadContentKnowledgePackFileInput) => ipcRenderer.invoke('contentKnowledgePack:readFile', input),
  listContentReviewTasks: (workspacePath: string) => ipcRenderer.invoke('contentReviewTasks:list', workspacePath),
  generateContentReviewTasks: (input: GenerateContentReviewTasksInput) => ipcRenderer.invoke('contentReviewTasks:generate', input),
  submitContentReviewDecision: (input: SubmitContentReviewDecisionInput) => ipcRenderer.invoke('contentReviewTasks:submitDecision', input),
  createContentProductionHandoff: (input: CreateContentProductionHandoffInput) => ipcRenderer.invoke('contentProductionHandoff:create', input),
  writeBackContentMaterialCoverage: (input: WriteBackContentMaterialCoverageInput) => ipcRenderer.invoke('contentMaterialCoverage:writeBack', input),
  listInputSources: (workspacePath: string) => ipcRenderer.invoke('inputSources:list', workspacePath),
  registerInputSource: (input: RegisterInputSourceInput) => ipcRenderer.invoke('inputSources:register', input),
  removeInputSource: (workspacePath: string, sourceId: string) => ipcRenderer.invoke('inputSources:remove', workspacePath, sourceId),
  importInputSourceFromFile: (
    workspacePath: string,
    purpose: InputSourcePurpose,
    options?: ImportInputSourceFromFileOptions,
  ) => ipcRenderer.invoke('inputSources:importFromFile', workspacePath, purpose, options),
  listPromptDrafts: (workspacePath: string) => ipcRenderer.invoke('promptDrafts:list', workspacePath),
  generatePromptDraft: (input: GeneratePromptDraftInput) => ipcRenderer.invoke('promptDrafts:generate', input),
  createPromptDraftFromContent: (input: CreatePromptDraftFromContentInput) => ipcRenderer.invoke('promptDrafts:createFromContent', input),
  createTeamKnowledgePromptDraft: (input: CreateTeamKnowledgePromptDraftInput) => ipcRenderer.invoke('promptDrafts:createTeamKnowledge', input),
  updatePromptDraft: (input: UpdatePromptDraftInput) => ipcRenderer.invoke('promptDrafts:update', input),
  recordPromptDraftCopy: (input: RecordPromptDraftCopyInput) => ipcRenderer.invoke('promptDrafts:recordCopy', input),
  listAgentPromptSessions: (workspacePath: string) => ipcRenderer.invoke('agentPromptSessions:list', workspacePath),
  startAgentPromptSession: (input: StartAgentPromptSessionInput) => ipcRenderer.invoke('agentPromptSessions:start', input),
  continueAgentPromptSession: (input: ContinueAgentPromptSessionInput) => ipcRenderer.invoke('agentPromptSessions:continue', input),
  respondAgentPromptAction: (input: RespondAgentPromptActionInput) => ipcRenderer.invoke('agentPromptSessions:respondAction', input),
  attachAgentPromptSessionInputSources: (input: AttachAgentPromptSessionInputSourcesInput) => ipcRenderer.invoke('agentPromptSessions:attachInputSources', input),
  listOverlayCards: (workspacePath: string) => ipcRenderer.invoke('overlayCards:list', workspacePath),
  generateOverlayCards: (input: GenerateOverlayCardsInput) => ipcRenderer.invoke('overlayCards:generate', input),
  listAssetReviews: (workspacePath: string) => ipcRenderer.invoke('assetReviews:list', workspacePath),
  reviewAsset: (input: ReviewAssetInput) => ipcRenderer.invoke('assetReviews:review', input),
  listMixPackages: (workspacePath: string) => ipcRenderer.invoke('mixPackages:list', workspacePath),
  exportMixPackage: (input: ExportMixPackageInput) => ipcRenderer.invoke('mixPackages:export', input),
  recordMixPackageImportEvidence: (input: RecordMixPackageImportEvidenceInput) => ipcRenderer.invoke('mixPackages:recordImportEvidence', input),
  selectAssetFiles: (kind: AssetFileKind) => ipcRenderer.invoke('assets:selectFiles', kind),
  revealPath: (path: string) => ipcRenderer.invoke('assets:revealPath', path),
  exportAsset: (input: ExportAssetInput) => ipcRenderer.invoke('assets:export', input),
  exportMarkdown: (input: ExportMarkdownInput) => ipcRenderer.invoke('article:exportMarkdown', input),
  exportPlatformDraft: (input: ExportPlatformDraftInput) => ipcRenderer.invoke('article:exportPlatformDraft', input),
  listPlatformDrafts: (workspacePath: string) => ipcRenderer.invoke('article:listPlatformDrafts', workspacePath),
  readPlatformDraftCopyText: (input: ReadPlatformDraftCopyTextInput) => ipcRenderer.invoke('article:readPlatformDraftCopyText', input),
  generateArticle: (input: ArticleGenerationRequest) => ipcRenderer.invoke('article:generate', input),
  reverseReferencePrompt: (input: ReferenceReverseRequest) => ipcRenderer.invoke('referenceReverse:generate', input),
  analyzeVideo: (input: VideoBreakdownRequest) => ipcRenderer.invoke('video:analyze', input),
  generateVideoScript: (input: VideoScriptGenerationRequest) => ipcRenderer.invoke('video:script', input),
  evaluateVideoScript: (input: VideoScriptEvaluationRequest) => ipcRenderer.invoke('video:script:evaluate', input),
  rewriteVideoScriptShot: (input: VideoScriptShotRewriteRequest) => ipcRenderer.invoke('video:script:rewriteShot', input),
  listImageProductionTasks: (workspacePath: string) => ipcRenderer.invoke('imageProduction:listTasks', workspacePath),
  createImageProductionTask: (input: CreateImageProductionTaskInput) => ipcRenderer.invoke('imageProduction:createTask', input),
  updateImageProductionTask: (input: UpdateImageProductionTaskInput) => ipcRenderer.invoke('imageProduction:updateTask', input),
  updateShotPrompt: (input: UpdateShotPromptInput) => ipcRenderer.invoke('imageProduction:updateShotPrompt', input),
  appendShotGenerationLog: (input: AppendShotGenerationLogInput) => ipcRenderer.invoke('imageProduction:appendGenerationLog', input),
  generateImage: (input: ImageGenerationRequest) => ipcRenderer.invoke('image:generate', input),
  generateImageSkill: (input: GenerateImageSkillInput) => ipcRenderer.invoke('imageSkills:generate', input),
  importImageSkillFromFile: () => ipcRenderer.invoke('imageSkills:importFromFile'),
  generateVideo: (input: VideoGenerationRequest) => ipcRenderer.invoke('video:generate', input),
  submitGenerationTask: (input: SubmitGenerationTaskInput) => ipcRenderer.invoke('generationTasks:submit', input),
  listGenerationTasks: (workspacePath: string) => ipcRenderer.invoke('generationTasks:list', workspacePath),
  onGenerationTaskEvent: (callback: (event: GenerationTaskEvent) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: GenerationTaskEvent) => callback(payload);
    ipcRenderer.on('generationTasks:event', listener);
    return () => ipcRenderer.off('generationTasks:event', listener);
  },
  listGenerationLogs: (workspacePath: string) => ipcRenderer.invoke('generationLogs:list', workspacePath),
  updateGenerationLogReview: (input: UpdateGenerationLogReviewInput) => ipcRenderer.invoke('generationLogs:updateReview', input),

  runTask: (input: RunTaskInput) => ipcRenderer.invoke('agent:run', input),
  cancelTask: (taskId: string) => ipcRenderer.invoke('agent:cancel', taskId),
  getAppServerHealth: () => ipcRenderer.invoke('appServer:health'),
  runAppServerSmoke: () => ipcRenderer.invoke('appServer:smoke'),
  onAgentEvent: (taskId: string, callback: (event: AgentEvent) => void) => {
    const channel = `agent:event:${taskId}`;
    const listener = (_event: Electron.IpcRendererEvent, payload: AgentEvent) => callback(payload);
    ipcRenderer.on(channel, listener);
    return () => ipcRenderer.off(channel, listener);
  },
};

contextBridge.exposeInMainWorld('contentStudio', api);
