import type { ModuleKey, V2ModuleKey } from './types';
import type { V2FeatureActionSlot, V2FeatureActionTarget, V2FeatureSpec } from './v2FeatureTypes';

export const V2_FEATURES: Record<V2ModuleKey, V2FeatureSpec> = {
  'image-reference-reverse': {
    eyebrow: '图片 / 无知识库玩法',
    title: '对标图反推',
    description: '上传对标图、产品图和产品资料，反推构图、光线、文字区域和风格，不要求先建知识库。',
    scope: '参考图反推 -> Prompt 草稿 -> 图片生成',
    status: '可运行入口',
    primaryAction: '反推图片 Prompt',
    secondaryAction: '发送到图片生成',
    flow: ['参考图', '产品资料', '视觉反推', 'Prompt 草稿', '人工调整', '图片生成'],
    cards: [
      { title: '反推维度', text: '结构化输出构图、主体位置、光线、背景、文字区域、画幅和可复用风格。', items: ['构图与画幅', '自然光和背景', '文字留白区'] },
      { title: '合规边界', text: '只复用风格结构，不复制竞品可识别元素，不编造产品卖点。', items: ['去除竞品 Logo', '保留来源引用', 'Prompt 版本可追溯'] },
    ],
    preview: '竖版 4:5，产品位于右下三分之一，早餐桌自然光，左上保留标题空间，手机实拍感，细节真实。',
    table: [['参考图 A', '已上传', '构图 / 光线', '可分析'], ['产品资料', '待补充', '规格 / 卖点', '人工补齐'], ['Prompt v1', '草稿', '可编辑', '发送图片生成']],
  },
  'image-scene-prompts': {
    eyebrow: '图片 / 场景库',
    title: '场景提示词',
    description: '品牌 / 产品知识库先生成场景库，再由场景卡生成 UGC 手机实拍图片 / 图生视频提示词。',
    scope: '品牌 / 产品知识库 -> 场景库 -> 图片 / 视频 Prompt',
    status: '可运行入口',
    primaryAction: '生成提示词组',
    secondaryAction: '复制选中 Prompt',
    flow: ['读取知识库', '抽取场景卡', '确认字段', '生成提示词组', '复制 / 入队', '审核'],
    cards: [
      { title: '场景卡字段', text: '场景库不是 Prompt 文本列表，而是 Prompt 前的结构化中间层。', items: ['人群 / 问题 / 季节', '空间 / 动作 / 情绪', '镜头 / 合规 / 用途'] },
      { title: 'Prompt 产物', text: '同一个场景可输出图片、图生视频、文案和绿幕文案图 Prompt。', items: ['图片 Prompt', '视频 Prompt', '绿幕文案图 Prompt'] },
    ],
    preview: '场景卡：早餐后，妈妈把便携条包放进孩子书包侧袋。Prompt 强调自然光、真实手部动作、无广告棚拍感。',
    table: [['早餐后', '已确认', '图片 / 视频', '可生成'], ['办公抽屉', '待确认', '图片', '可编辑'], ['换季家庭', '已确认', '详情页', '可生成']],
  },
  'image-green-screen': {
    eyebrow: '图片 / 视频素材',
    title: '绿幕文案图',
    description: '从脚本或卖点列表拆出标题卡、卖点卡、金句卡和 CTA 卡，导出 PNG / WebP 并写入混剪 manifest。',
    scope: '脚本 / 卖点 -> 绿幕文案图 -> 混剪 manifest',
    status: '可运行入口',
    primaryAction: '生成绿幕图',
    secondaryAction: '写入 manifest',
    flow: ['导入脚本', '拆文案卡', '选择版式', '生成图片', '可读性审核', '导出'],
    cards: [
      { title: '文案拆分', text: '文案过长时提示拆分，不强行压缩到不可读。', items: ['标题卡', '卖点卡', '金句卡', 'CTA 卡'] },
      { title: '导出字段', text: '每张图记录用途、画幅、出现时长、背景类型和关联脚本段落。', items: ['duration', 'overlayType', 'scriptRef'] },
    ],
    preview: '标题卡：早餐后 10 秒钟的小习惯。卖点卡：便携条包，放进包里或抽屉都不占地方。',
    table: [['标题卡 01', '通过', '9:16 PNG', '入 manifest'], ['卖点卡 03', '需拆分', '文案过长', '待处理'], ['CTA 卡', '草稿', '透明背景', '可导出']],
  },
  'image-compliance': {
    eyebrow: '图片 / 审核',
    title: '合规检测',
    description: '检查图片、文案和 Prompt 是否存在医疗化承诺、绝对化表达、竞品元素复制和事实不一致。',
    scope: '候选素材 -> 合规审核 -> 入库 / 回炉',
    status: '审核入口',
    primaryAction: '执行合规检测',
    secondaryAction: '提交人工审核',
    flow: ['读取产物', '事实检查', '合规检查', '标记风险', '人工确认', '入库'],
    cards: [
      { title: '检测维度', text: '事实、合规、品牌口吻、图片文字可读性和 AI 味统一进入审核清单。', items: ['事实一致性', '禁用表达', '视觉可读性'] },
      { title: '恢复路径', text: '不删除失败产物，保留驳回原因并允许回到 Prompt 版本重生成。', items: ['驳回原因', '重生成入口', '保留原产物'] },
    ],
    preview: '风险：出现“见效更快”表达，建议替换为“更容易坚持的日常补充场景”。',
    table: [['图片 02', '通过', '无高风险表达', '可入库'], ['文案卡 03', '风险', '绝对化表达', '需改写'], ['Prompt v4', '注意', '医疗化词汇', '人工确认']],
  },
  'image-retouch': {
    eyebrow: '图片 / 后处理',
    title: '图片精修',
    description: '对通过初筛的图片做局部修复、裁切、扩图、文字区域清理和版本对比，保留原图与 Prompt 来源。',
    scope: '通过素材 -> 精修版本 -> 审核 / 模板回炉',
    status: '回炉入口',
    primaryAction: '创建精修版本',
    secondaryAction: '回炉为模板',
    flow: ['选择图片', '标记区域', '精修 / 扩图', '版本对比', '审核', '回炉'],
    cards: [
      { title: '精修动作', text: '只处理当前选中图片，不改写原始素材和生成记录。', items: ['局部修复', '扩图', '文字区域清理'] },
      { title: '回炉沉淀', text: '通过审核的好图可以反推质量原因、标签和模板草稿。', items: ['Prompt 模板', '场景标签', 'Skill 草稿'] },
    ],
    preview: '精修说明：清理左上角多余文字阴影，保留产品位置和自然光质感。',
    table: [['原图 02', '已通过', '可精修', '保留'], ['v2-clean', '草稿', '文字区清理', '待审'], ['模板草稿', '未创建', '回炉入口', '可操作']],
  },
  'video-script': {
    eyebrow: '视频 / 脚本',
    title: '视频脚本',
    description: '基于参考视频拆解、图片素材、品牌 / IP 知识库和卖点生成脚本、分镜和字幕结构。',
    scope: '参考视频 / 图片素材 -> 脚本 -> 分镜 Prompt',
    status: '可运行入口',
    primaryAction: '生成脚本',
    secondaryAction: '拆成绿幕卡',
    flow: ['选择卖点', '选择风格', '生成脚本', '确认分镜', '生成 Prompt', '导出'],
    cards: [
      { title: '脚本结构', text: '用钩子、场景、卖点、证明和 CTA 组织短视频脚本。', items: ['钩子', '场景', 'CTA'] },
      { title: '知识引用', text: 'IP 类脚本保持人设口吻；产品类脚本保持事实和合规边界。', items: ['IP 口吻', '产品事实', '禁用表达'] },
    ],
    preview: '0-3s：坚持一件小事最难的是开始。3-9s：早餐后顺手放一包进包里。9-15s：把复杂动作变成日常习惯。',
    table: [['脚本 v1', '草稿', '15 秒', '待确认'], ['字幕卡', '可生成', '3 张', '绿幕图'], ['分镜 Prompt', '待生成', '5 段', '视频 Prompt']],
  },
  'video-prompt': {
    eyebrow: '视频 / 外部生成',
    title: '视频 Prompt',
    description: '生成可复制到第三方平台的 15 秒视频 Prompt。软件只记录 Prompt 和复制动作，第三方生成过程脱离软件。',
    scope: '图片素材 / 场景卡 -> 视频 Prompt -> 外部生成记录',
    status: '可运行入口',
    primaryAction: '复制视频 Prompt',
    secondaryAction: '导入成品视频',
    flow: ['选择场景', '生成 Prompt', '复制外部', '第三方生成', '手动导入', '入库'],
    cards: [
      { title: '外部边界', text: '不创建外部任务、不轮询状态、不绑定外部任务 ID。', items: ['只记录复制动作', '追溯原 Prompt', '成品手动导入'] },
      { title: '内部可选', text: '当成本可接受时可走内部视频 API，但不是默认主路径。', items: ['Vidu / Runway 抽象', '真实 provider', 'blocked 状态'] },
    ],
    preview: '15 秒，9:16，早餐桌自然光，手拿条包入镜，倒入水杯后放回书包侧袋，镜头轻微手持。',
    table: [['Prompt v3', '已复制外部', '第三方平台', '等待手动导入'], ['成品视频', '未导入', '本地文件', '可选'], ['内部 API', '未启用', '成本高', 'blocked']],
  },
  'video-import': {
    eyebrow: '视频 / 入库',
    title: '成品视频导入',
    description: '第三方生成后由用户手动导入视频文件，并选择关联原 Prompt、图片素材和 SOP 运行记录。',
    scope: '第三方成品视频 -> 手动导入 -> 素材审核入库',
    status: '可运行入口',
    primaryAction: '导入成品视频',
    secondaryAction: '关联原 Prompt',
    flow: ['选择文件', '关联 Prompt', '补充标签', '生成缩略图', '审核', '入素材库'],
    cards: [
      { title: '导入字段', text: '不要求外部任务 ID，只记录本地文件和本软件内的 Prompt 来源。', items: ['文件路径', 'PromptRef', '输入素材'] },
      { title: '审核', text: '导入后仍需要人工确认用途、画幅、时长和合规状态。', items: ['通过', '驳回', '入库标签'] },
    ],
    preview: '导入 mp4，关联“视频 Prompt v3”和图片候选 02，打上早餐场景、9:16、15s 标签。',
    table: [['video-clip-001', '待导入', 'mp4', '选择文件'], ['Prompt v3', '已关联', '视频 Prompt', '可追溯'], ['素材库', '待审核', '视频素材', '入库']],
  },
  'video-mix-export': {
    eyebrow: '视频 / 导出',
    title: '混剪包导出',
    description: '导出第三方混剪软件可读取的素材文件夹和 manifest，包含图片、绿幕图、可选视频、文案字段、标签和用途。',
    scope: '通过素材 -> 素材文件夹 -> 混剪 manifest',
    status: '可运行入口',
    primaryAction: '导出混剪包',
    secondaryAction: '预览 manifest',
    flow: ['选择通过素材', '补齐标签', '生成 manifest', '导出文件夹', '交给混剪软件'],
    cards: [
      { title: '包结构', text: 'v2 不做时间线剪辑和成片渲染，只准备可混剪素材包。', items: ['images/', 'overlays/', 'videos/'] },
      { title: 'manifest 字段', text: '包含素材用途、画幅、时长、文案、平台、PromptRef 和来源运行。', items: ['assetId', 'duration', 'promptRef'] },
    ],
    preview: '{ platform: "douyin", assets: ["image_001.png", "overlay_title_001.png"], promptRef: "video-prompt-v3" }',
    table: [['图片素材', '18 张', '通过审核', '导出'], ['绿幕图', '8 张', '通过审核', '导出'], ['视频片段', '3 条', '可选', '导出']],
  },
  'video-creative': {
    eyebrow: '视频 / 创意',
    title: '创意视频',
    description: '围绕品牌 / IP 资产生成氛围视频、产品场景动效和短片段创意方向，最终沉淀为视频 Prompt 或素材包。',
    scope: '成功素材 / 场景库 -> 创意方向 -> 视频 Prompt',
    status: 'Prompt 入口',
    primaryAction: '生成创意方向',
    secondaryAction: '转为视频 Prompt',
    flow: ['选择资产', '生成方向', '确认风格', '生成 Prompt', '复制外部', '导入素材'],
    cards: [
      { title: '创意来源', text: '可来自成功图片、IP 语气、品牌场景库或爆款视频拆解。', items: ['成功素材', '场景库', '拆解报告'] },
      { title: '产物边界', text: '不承诺成片，只输出可执行的视频 Prompt 和素材建议。', items: ['氛围动效', '产品场景', '镜头语言'] },
    ],
    preview: '从早餐桌静物图过渡到书包侧袋近景，强调“顺手放进去”的低门槛动作。',
    table: [['方向 01', '生活化', '15s', '可转 Prompt'], ['方向 02', '产品近景', '8s', '可转 Prompt'], ['方向 03', 'IP 口播', '20s', '需脚本']],
  },
  'video-custom': {
    eyebrow: '视频 / 自定义',
    title: '自定义视频',
    description: '高级用户配置时长、画幅、镜头段落、参考图、参考视频和 provider，普通用户仍走表单化 Prompt。',
    scope: '自定义镜头表单 -> 视频 Prompt -> 复制或内部执行',
    status: 'Prompt 入口',
    primaryAction: '保存视频配置',
    secondaryAction: '生成 Prompt',
    flow: ['填写字段', '配置镜头', '选择 provider', '生成 Prompt', '执行 / 复制', '记录'],
    cards: [
      { title: '字段配置', text: '不把节点图暴露给普通用户，用表单控制镜头、动作、时长和输出。', items: ['时长', '画幅', '镜头段落'] },
      { title: 'Provider 状态', text: '未配置真实服务时只保留 blocked 请求，不伪造成果。', items: ['internal-api', 'manual prompt', 'blocked'] },
    ],
    preview: '镜头 1：产品特写 3s；镜头 2：手部动作 6s；镜头 3：场景收束 6s。',
    table: [['镜头段', '5 段', '完整', '可运行'], ['Provider', '未配置', '内部 API', 'blocked'], ['外部复制', '可用', '手动', '推荐']],
  },
  'article-title': {
    eyebrow: '文案 / 标题',
    title: '标题生成',
    description: '围绕平台、场景卡、痛点和 IP / 品牌口吻生成标题矩阵，并保留来源和禁用表达。',
    scope: '痛点 / 场景 / 平台 -> 标题矩阵 -> 正文入口',
    status: 'Prompt 入口',
    primaryAction: '生成标题矩阵',
    secondaryAction: '发送到文章',
    flow: ['选择平台', '选择痛点', '生成标题', '评分筛选', '发送正文', '入库'],
    cards: [
      { title: '标题角度', text: '从评论、差评和客服问题中聚类痛点，输出真实用户语言。', items: ['问题型', '场景型', '反常识型'] },
      { title: '平台差异', text: '同一素材可生成小红书、公众号、视频号不同标题。', items: ['小红书', '公众号', '视频号'] },
    ],
    preview: '早餐后这 10 秒，才是最容易坚持的小习惯。',
    table: [['标题组 A', '小红书', '种草', '待选'], ['标题组 B', '公众号', '深度', '待选'], ['标题组 C', '视频号', '口播', '可发送']],
  },
  'article-script': {
    eyebrow: '文案 / 脚本',
    title: '脚本生成',
    description: '生成口播脚本、分镜脚本和绿幕文案图内容，可接入视频 Prompt 和混剪包。',
    scope: '知识引用 / 卖点 -> 口播脚本 -> 绿幕文案图',
    status: 'Prompt 入口',
    primaryAction: '生成脚本',
    secondaryAction: '拆成绿幕图',
    flow: ['选择知识', '生成口播', '拆分字幕', '生成绿幕图', '视频 Prompt', '导出'],
    cards: [
      { title: '脚本类型', text: '支持短视频口播、产品讲解、IP 观点和私域回复。', items: ['口播', '分镜', '字幕卡'] },
      { title: '下游联动', text: '脚本可以进入视频 Prompt、绿幕文案图和混剪包。', items: ['视频 Prompt', '绿幕图', 'manifest'] },
    ],
    preview: '很多人不是不想坚持，而是动作太复杂。把它变成早餐后顺手做的一件事，门槛就低很多。',
    table: [['口播 v1', '草稿', '60s', '待审'], ['短视频 v1', '可用', '15s', '可转 Prompt'], ['字幕卡', '8 张', '待生成', '绿幕图']],
  },
  'knowledge-brand': {
    eyebrow: '知识库 / 品牌链路',
    title: '品牌 / 产品知识库',
    description: '先抽取品牌调性、产品事实、卖点、目标人群和合规边界，再进入场景库生成下游 Prompt。',
    scope: '品牌 / 产品文档 -> 结构化知识库 -> 场景库',
    status: '可运行入口',
    primaryAction: '抽取品牌知识库',
    secondaryAction: '生成场景库',
    flow: ['导入 DOCX', '抽取事实', '确认卖点', '标注合规', '生成场景库', '生成提示词组'],
    cards: [
      { title: '抽取结果', text: '把 DOCX 中的事实、卖点、人群和禁用表达结构化，但不替代原文。', items: ['产品事实', '目标人群', '合规边界'] },
      { title: '下游边界', text: '品牌知识库不能直接跳 Prompt，中间必须有场景卡或内容任务结构。', items: ['场景库', '卖点卡', 'Prompt 组'] },
    ],
    preview: '合规边界：避免“治疗、见效、最强、根治”等承诺；优先表达使用场景、坚持门槛和便携性。',
    table: [['品牌调性', '已抽取', '温和可信', '可确认'], ['卖点卡', '12 条', '待审核', '可编辑'], ['场景库', '未生成', '下一步', '主按钮']],
  },
  'knowledge-scenes': {
    eyebrow: '知识库 / 中间层',
    title: '场景库',
    description: '场景库是 Prompt 前的中间层，承接品牌 / 产品知识库和 IP 运营场景，向图片、文案和视频 Prompt 下游输出。',
    scope: '场景卡 -> 图片 Prompt / 视频 Prompt / 文案 Prompt',
    status: '可运行入口',
    primaryAction: '生成提示词组',
    secondaryAction: '发送到图片生成',
    flow: ['场景卡', '用户确认', 'Prompt 组', '图片生成', '视频 Prompt', '文案生成'],
    cards: [
      { title: '场景字段', text: '人群、问题、季节、空间、动作、情绪、镜头、合规边界和输出用途。', items: ['早餐后', '办公室', '换季'] },
      { title: '输出用途', text: '同一场景可生成图片 Prompt、图生视频 Prompt、文案 Prompt 和绿幕文案图 Prompt。', items: ['图片', '视频', '文案'] },
    ],
    preview: '场景卡：办公室抽屉备货，午后自然光，同事递水杯，重点表达“随手就能坚持”。',
    table: [['早餐后', '已确认', '图片 / 视频', '可生成'], ['办公抽屉', '待确认', '图片', '可编辑'], ['换季家庭', '已确认', '详情页', '可生成']],
  },
  'knowledge-ip': {
    eyebrow: '知识库 / IP 体系',
    title: 'IP 知识库',
    description: '个人 IP 全面运营底座，包含身份、价值观、语言、判断、素材和创作引擎六层，不是品牌知识库的字段。',
    scope: 'IP 素材 -> 六层知识库 -> 场景延伸库',
    status: '可运行入口',
    primaryAction: '构建 IP 知识库',
    secondaryAction: '生成场景延伸库',
    flow: ['导入素材', 'Agent 读取', '生成六层', '补齐缺口', '导出知识库', '延伸场景'],
    cards: [
      { title: '六层结构', text: '身份锚定、价值观立场、声音语言、判断方法、内容素材、创作引擎。', items: ['身份', '语言', '创作引擎'] },
      { title: '场景延伸', text: '口播、朋友圈、私域、产品化和咨询回复都引用同一 IP 知识库版本。', items: ['口播', '私域', '产品化'] },
    ],
    preview: '待补齐：判断方法层缺少具体案例；内容素材层缺少可公开故事；创作引擎层需要栏目模板。',
    table: [['身份锚定', '完整', '已确认', '可导出'], ['判断方法', '缺口', '待补案例', '需追问'], ['创作引擎', '草稿', '栏目模板', '待确认']],
  },
  'knowledge-inputs': {
    eyebrow: '知识库 / 输入源',
    title: '输入源 / 文档转换',
    description: '登记 DOCX、Markdown、参考图、参考视频、产品资料、SKU 表、竞品内容、评论和历史成功素材。',
    scope: '文件 / 文本 / 参考素材 -> 输入源记录 -> SOP 分流',
    status: '可运行入口',
    primaryAction: '登记输入源',
    secondaryAction: '转换为 Markdown',
    flow: ['选择文件', '解析类型', '转换文本', '补充标签', '入输入源', '分流 SOP'],
    cards: [
      { title: '输入类型', text: '不只有知识库，参考图、参考视频、SKU 表和历史素材都能驱动 SOP。', items: ['DOCX', '参考图', 'SKU 表'] },
      { title: '失败状态', text: '文件无法解析时保留原文件并标记 blocked 原因，不伪造成功。', items: ['保留原文件', '错误原因', '重试入口'] },
    ],
    preview: '转换队列：嘉文老师_IP知识库_v1.0.docx -> markdown；参考视频 01 -> analyze；SKU 表 -> ProductBrief。',
    table: [['DOCX', '已转换 2', '待转换 1', '可重试'], ['参考视频', '待分析', '视频理解', 'blocked'], ['SKU 表', '可解析', '变量表', '可运行']],
  },
  'assets-prompt-workbench': {
    eyebrow: '资产 / 玩法跑通',
    title: 'Prompt 工作台',
    description: '服务还没有固定 SOP 的探索阶段：多源输入、用户意图、Agent 多轮调整、Prompt 草稿版本和物化入口。',
    scope: '多源输入 -> Agent 会话 -> Prompt 草稿 -> SOP 草案',
    status: '可运行入口',
    primaryAction: '生成 Prompt',
    secondaryAction: '物化为 SOP',
    flow: ['选择输入源', '输入意图', 'Agent 追问', '确认 Prompt', '版本对比', '物化'],
    cards: [
      { title: '适用场景', text: '当玩法还没固化时先跑通 Prompt，而不是先做复杂工作流。', items: ['读文档', '看图反推', '视频拆解'] },
      { title: '物化入口', text: '确认过的 Prompt 草稿可沉淀为 Prompt Pack、SOP 或 Skill。', items: ['Prompt Pack', 'SOP', 'Skill'] },
    ],
    preview: 'Prompt v5：根据产品知识库和早餐场景库，生成 10 组 UGC 手机实拍提示词。',
    table: [['Prompt v3', '已淘汰', '太广告感', '保留历史'], ['Prompt v5', '待确认', '更自然', '可物化'], ['SOP 草案', '未上线', '人工确认', '待保存']],
  },
  'assets-sop': {
    eyebrow: '资产 / 表单执行',
    title: 'SOP 工作流',
    description: '普通用户默认走表单化 SOP 执行页，不进入 canvas。每个 SOP 定义输入源、字段、步骤、审核规则和导出规则。',
    scope: 'SOP 表单 -> 步骤执行 -> 审核入库 -> 导出',
    status: '可运行入口',
    primaryAction: '运行 SOP',
    secondaryAction: '生成 SOP 草案',
    flow: ['输入源', '字段表单', '步骤执行', '人工审核', '入库', '导出'],
    cards: [
      { title: 'SOP 示例', text: '小红书种草图、公众号 IP 内容、详情页素材、视频素材包。', items: ['小红书', '公众号', '详情页'] },
      { title: '运行记录', text: '保存输入源、Agent 会话、Prompt 版本、模型、产物、错误和来源引用。', items: ['RunId', 'PromptVersion', 'Artifact'] },
    ],
    preview: '小红书种草图 SOP：产品图 + 参考图 + 产品资料 -> 反推风格 -> 结构化卖点 -> Prompt -> 4 张图 -> 质检 -> 人审 -> 入库。',
    table: [['小红书种草图', 'P0', '可运行', '表单'], ['公众号 IP 内容', 'P0', '可运行', 'Agent 读文档'], ['视频素材包', 'P1', '草案', '待确认']],
  },
  'assets-history': {
    eyebrow: '资产 / 审计',
    title: '运行历史',
    description: '用于复盘、重试和审计。查看每次运行的输入、输出、步骤耗时、模型、失败原因和产物列表。',
    scope: '运行记录 -> 步骤轨迹 -> blocked 恢复 / 复用输入',
    status: '可运行入口',
    primaryAction: '查看运行详情',
    secondaryAction: '复用输入',
    flow: ['运行列表', '步骤详情', '输入输出', '日志', '重试', '复用'],
    cards: [
      { title: '详情结构', text: '左侧步骤列表，中间步骤输入输出，右侧产物和来源引用。', items: ['步骤', '日志', '产物'] },
      { title: '失败处理', text: '失败不跳过、不伪造；保留 provider、错误和恢复路径。', items: ['blocked', '重试', '配置 provider'] },
    ],
    preview: 'run_20260520_001：图片 provider 未配置，图片生成步骤 blocked；已保存 Prompt 和输入源，可在配置后重试。',
    table: [['run_001', 'blocked', '图片 provider 未配置', '可重试'], ['run_002', '完成', '4 张图片', '可复用'], ['run_003', '待审核', '视频 Prompt', '查看详情']],
  },
  'workflow-definition': {
    eyebrow: '管理 / WorkflowDefinition',
    title: '工作流定义',
    description: '维护 SOP 的输入源、字段、步骤、依赖、输出、审核规则和导出格式。定义可版本化、可 diff、可执行。',
    scope: '工作流定义 -> 版本保存 -> 发布为可运行 SOP',
    status: '可运行入口',
    primaryAction: '保存定义版本',
    secondaryAction: '发布为可运行',
    flow: ['编辑字段', '编辑步骤', '配置依赖', '配置审核', '保存版本', '发布'],
    cards: [
      { title: '定义结构', text: '工作流事实源是可执行定义，不是画布坐标。', items: ['inputSchema', 'steps', 'outputs'] },
      { title: '上线规则', text: '草案不能直接上线，必须人工确认步骤、provider、审核和导出规则。', items: ['草案', '审核', '发布'] },
    ],
    preview: 'xiaohongshu-seeding-image@v0.2：reference_reverse -> product_structuring -> prompt_generate -> image_generate -> review -> asset_store',
    table: [['小红书种草图', 'v0.2', '草案', '待发布'], ['公众号 IP 内容', 'v0.1', '可运行', '已发布'], ['视频素材包', 'v0.1', '草案', '需审核']],
  },
  'workflow-canvas': {
    eyebrow: '管理 / 高级视图',
    title: 'Canvas 编排',
    description: 'Canvas 只作为高级用户查看和编辑复杂依赖的视图，读写同一份工作流定义，不成为普通用户主入口。',
    scope: '同一份工作流定义 -> Canvas 高级视图 -> 表单执行',
    status: '高级视图',
    primaryAction: '打开 Canvas',
    secondaryAction: '同步定义',
    flow: ['读取定义', '显示节点', '调整依赖', '保存定义', '表单运行'],
    cards: [
      { title: '边界', text: '普通用户不用 canvas 也能完成 SOP；Canvas 不能取代表单执行页。', items: ['非主入口', '非事实源', '高级编辑'] },
      { title: '节点类型', text: '节点对应工作流步骤：输入源、Agent 读取、参考图反推、视频拆解、生成、审核和导出。', items: ['输入源', 'Agent', '审核'] },
    ],
    preview: '品牌知识库 -> 场景库 -> Prompt 组 -> 图片生成 -> 审核 -> 素材库。保存后同步 WorkflowDefinition。',
    table: [['节点图', '可查看', '高级用户', '非主入口'], ['定义同步', '可保存', 'WorkflowDefinition', '事实源'], ['运行', '表单执行', '普通用户', '推荐']],
  },
};

const V2_FEATURE_ACTION_TARGETS: Partial<
  Record<V2ModuleKey, Partial<Record<V2FeatureActionSlot, V2FeatureActionTarget>>>
> = {
  'image-reference-reverse': {
    secondary: { type: 'module', module: 'image' },
  },
  'image-scene-prompts': {
    secondary: { type: 'module', module: 'image' },
  },
  'image-green-screen': {
    secondary: { type: 'module', module: 'video-mix-export' },
  },
  'video-script': {
    secondary: { type: 'module', module: 'image-green-screen' },
  },
  'video-prompt': {
    secondary: { type: 'module', module: 'video-import' },
  },
  'video-import': {
    secondary: { type: 'module', module: 'video-prompt' },
  },
  'video-mix-export': {
    secondary: { type: 'module', module: 'assets-history' },
  },
  'article-title': {
    secondary: { type: 'module', module: 'article' },
  },
  'article-script': {
    secondary: { type: 'module', module: 'image-green-screen' },
  },
  'knowledge-brand': {
    primary: { type: 'module', module: 'knowledge-scenes' },
    secondary: { type: 'module', module: 'knowledge' },
  },
  'knowledge-scenes': {
    primary: { type: 'module', module: 'image-scene-prompts' },
    secondary: { type: 'module', module: 'image' },
  },
  'knowledge-ip': {
    primary: { type: 'module', module: 'knowledge' },
    secondary: { type: 'module', module: 'knowledge-scenes' },
  },
  'knowledge-inputs': {
    primary: { type: 'module', module: 'knowledge' },
  },
  'assets-prompt-workbench': {
    secondary: { type: 'module', module: 'assets-sop' },
  },
  'assets-sop': {
    secondary: { type: 'module', module: 'workflow-definition' },
  },
  'assets-history': {
    secondary: { type: 'module', module: 'assets' },
  },
  'workflow-canvas': {
    primary: { type: 'module', module: 'workflow-definition' },
    secondary: { type: 'module', module: 'workflow-definition' },
  },
};

export function isV2FeatureModule(module: ModuleKey): module is V2ModuleKey {
  return Object.prototype.hasOwnProperty.call(V2_FEATURES, module);
}

export function getV2FeatureActionTarget(
  module: V2ModuleKey,
  slot: V2FeatureActionSlot,
): V2FeatureActionTarget | undefined {
  return V2_FEATURE_ACTION_TARGETS[module]?.[slot];
}
